name: Build Windows EXE

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true

      - name: Install gems
        run: bundle install

      - name: Build exe
        run: bundle exec ocra tbn.rb --console --output cleaning_duty.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cleaning-duty-exe
          path: cleaning_duty.exe